memo/urls.py
from django.contrib import admin
from django.urls import path,include#include追加する
from django.views.generic import RedirectView

from django.conf.urls.static import static # 追加
from django.conf import settings # 追加



urlpatterns = [
    path('admin/', admin.site.urls),
    path('spdiary/',include('spdiary.urls')),
    path('',RedirectView.as_view(url='/spdiary/login/')),
    #path('image/', include('spdiary.urls')), 

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 追加

spdiary/urls.py
from django.urls import path
#from .views import DiaryApp
from django.contrib.auth import views as auth_views
from .views import SignupPage
from .views import DiaryCreateView
from .views import DiaryListView
from .views import DiaryDetailView,DiaryUpdateView,DiaryDeleteView

from .views import ListPage,CreatePage,UpdatePage,DeletePage
from .views import ImageCreateView,ImageListView,ImageDetailView,ImageDeleteView

app_name = "spdiary"

urlpatterns = [
    #register
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignupPage.as_view(), name='signup'),
    #Diary
    path('create/', DiaryCreateView.as_view(), name='create'),
    path('list/', DiaryListView.as_view(), name='list'),
    path('detail/<uuid:pk>/',DiaryDetailView.as_view(), name = 'detail'), 
    path('update/<uuid:pk>/',DiaryUpdateView.as_view(), name = 'update'), 
    path('delete/<uuid:pk>/',DiaryDeleteView.as_view(),name='delete'),
    #imageリスト
    path('Image/',ImageCreateView.as_view(),name='Image'),
    path('ImageList/',ImageListView.as_view(),name='ImageList'),
    path('ImageDetail/<int:pk>/', ImageDetailView.as_view(), name='ImageDetail'),
    path('ImageDelete/<int:pk>/', ImageDeleteView.as_view(), name='ImageDelete'),
    #Todoリスト
    path('ListPage/',ListPage.as_view(),name='ListPage'),
    path('CreatePage/',CreatePage.as_view(),name='CreatePage'),
    path('UpdatePage/<int:pk>/',UpdatePage.as_view(),name='UpdatePage'),
    path('DeletePage/<int:pk>/',DeletePage.as_view(),name='DeletePage'),
]

spdiary/models.py
from django.db import models
from django.utils import timezone#追加する
import uuid#追加する
from django.contrib.auth.models import User

class Todo(models.Model):
    time = models.DateField(verbose_name="作成日", default=timezone.now)
    memo = models.TextField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)#自動でつく
    date = models.DateField(verbose_name='日付', default=timezone.now)#日付
    title = models.CharField(verbose_name='タイトル', max_length=255)#日付のタイトル
    text = models.TextField(verbose_name='本文',blank=True,null=True,max_length=1000)#日付の本文
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)#作成日時
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)#編集日時
    tagname = models.CharField(verbose_name='タグ', max_length=40,null=True,blank=True)#タグを書くスペース
    tag = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    def __str__(self):
            return self.title
    

class Image(models.Model):
    name = models.CharField(verbose_name='題名',max_length=40)
    image = models.ImageField(upload_to='img/upload')
    memo = models.TextField(verbose_name='メモ',max_length=60,null=True,blank=True)
    today = models.DateTimeField(verbose_name='作成日', default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
     
    def __str__(self):
            return self.name

templates/image/Image.html
{% extends './base.html' %}
{% block content %}

<body>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">アップロード</button>
    </form>
<hr />
</body>
</html>
{% endblock %}

templates/image/ImageDelete.html
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{image.id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">PHOTOの削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>PHOTOを削除してもよろしいですか ?</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'spdiary:ImageDelete' image.id %}">{% csrf_token %}
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">閉じる</button>
                    <button type="submit" class="btn btn-outline-success">削除</button>
                </form>
        </div>
        </div>
    </div>
</div>

templates/image/ImageDetail.html
{% extends './base.html' %}
{% block content %}
<style>
    .title{/*タイトル*/
        left:20%;
        top:23%;
        position: absolute;
        font-size: 30px;
    }
    .photo{/*写真*/
        left:60%;
        top:20%;
        position: absolute;
    }
    .today{/*日付*/
        left:17%;
        top:43%;
        position: absolute;
        font-size: 20px;
    }
    .big{/*ボックス*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 20%;
        width: 300px;
        height: 80px;
        border-radius: 20px;
    }
    .box{/*メモ*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 40%;
        width: 400px;
        height: 150px;
        border-radius: 20px;

    }
    .memo{/*メモ本文*/
        left:17%;
        top:50%;
        position: absolute;
        font-size: 20px;
    }
    .delete{/*削除ボタン*/
        width: 150px;
        min-height: 44px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 35%;
        bottom: 23%;
    }    
</style>

<body>
    <div class="big"></div>
    <div class="box"></div>
    <div>
        <div class="title">{{ image.name }}</div>
        <div class="today">{{image.today|date:"m月d日"}}</div>
        <div class="memo">{{ image.memo }}</div>
        <div class="photo">
        <img src="{{ image.image.url  }}" width="300px">
        </div>
    </div>
    <button type="button" class="delete" data-bs-toggle="modal" data-bs-target="#deleteModal-{{image.id}}">削除する</button>
                            {% include 'image/ImageDelete.html' %}
</body>

{% endblock %}

templates/image/ImageList.html
{% extends './base.html' %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<style>
    .create{/*編集ボタン*/
      position:absolute;
      background-color:#bbf9c9;
      border-radius: 20px;
      left:72%;
      bottom:35%;
      color:rgb(237, 22, 18);
      font-size:18px;
      font-family: monospace;
      width: 210px;
      line-height: 38px;
      min-height: 48px; 
    }
    .list{/*ホームボタン*/
    border: none;
    position:absolute;
    background-color:#bbf9c9;
    border-radius: 20px;
    left:72%;
    bottom:23%;
    font-size:18px;
    font-family: monospace;
    width: 210px;
    line-height: 38px;
    min-height: 46px;   
    }
    .yohaku{
        margin:8px 45px;
    }

    .photo img{
    object-fit: cover;
    height: 200px;
    width: 200px;
  }

  input[name="query" ]{
    background-color: #FFF ;
    left:67%;
    position: absolute;
    font-size:21px;
    border-radius: 10px;
    top:19%;
  }

    .button{/*検索フォーム*/
    -moz-appearance: none;
    -webkit-appearance: none;
    appearance: none;

    margin: 1em 0; /* 前後の隙間 */
    padding: 0.6em 1em; /* 塗りの余白 */
    font-size: 1em; /* フォントサイズ */
    background-color: #9dc5a8; ; /* 背景色 */
    border: 0; /* 枠線を消す */
    transition: 0.3s; /* ホバーの変化を滑らかに */
    left:88.4%;
    position: absolute;
    border-radius: 10px; 
    top:16.5%;


  }
  .button:hover {/*検索ボタン*/
  background-color: #7d9f87; ; /* 背景色 */
  }


</style>
<body>
    <div class="big-box"></div>
    <div class="bg-light p-3 p-sm-5 mb-4 border-top">
      <div class="container">
        <h1 class="display-6">Welcome to "Memory Map"</h1>
        <p style="font-size:20px; padding-left:30%;">- PHOTO -</p>
      </div>
    </div>

    <div class="container">
      {% csrf_token%}
      <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text" placeholder="タイトルで検索"/>
        <button type="submit" class="button">検索する</button>
      </form>
    </div>

  <div class="container">    
  {% for image in image_list %}
  <div class="card mb-4" style="max-width: 540px; left:8%; background-color: #b8f7c7; border-radius:10px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ image.image.url }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'spdiary:ImageDetail' image.id %}">{{ image.name }}</a></h5>
          <p class="card-text"><small class="text-body-secondary">{{ image.today|date:"m月d日"}}</small></p>
          <h6 class="card-text">{{ image.memo }}</h6>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

<a class="list" href="{% url 'spdiary:list' %}"><span class="yohaku">日記作成 →</span></a>
<a class="create" href="{% url 'spdiary:Image' %}"><span class="yohaku">新規作成　→</span></a>
</body>
{% endblock %}

templates/image/Imagedelete.html
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{image.id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">PHOTOの削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>PHOTOを削除してもよろしいですか ?</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'spdiary:ImageDelete' image.id %}">{% csrf_token %}
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">閉じる</button>
                    <button type="submit" class="btn btn-outline-success">削除</button>
                </form>
        </div>
        </div>
    </div>
</div>

templates/image/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="ja">   
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memory Map</title>
</head>
<body style="padding-top: 4rem;">

    <div class='fixed-top'>
        <nav class="navbar navbar-expand-lg" style="background-color:#b8f7c7; font-size: 20px;">
            <a class="navbar-brand" href="{% url 'spdiary:list' %}">&nbsp;&nbsp;Memory Map<span class="sr-only"></span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'spdiary:list' %}">&nbsp;&nbsp;DIARY</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'spdiary:ListPage' %}">&nbsp;&nbsp;TODO</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'spdiary:ImageList' %}">&nbsp;&nbsp;PHOTO</a>
              </ul>
            </div>

            <ul class="navbar-nav mr-md-2">
                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'spdiary:logout' %}">ログアウト</a></li>
                </ul>
                {% else %}
                <a class="btn btn-outline-light btn-sm" href="{% url 'spdiary:login' %}">ログイン</a></li>
                {% endif %}
            </ul>  
        </nav>  
    </div>

    
    {% block content %}
    {% endblock %}
</body>
</html>

templates/image/image.html
{% extends './base.html' %}
{% block content %}

<body>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">アップロード</button>
    </form>
<hr />
</body>
</html>
{% endblock %}

templates/image/imagedelete.html
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{image.id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">PHOTOの削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>PHOTOを削除してもよろしいですか ?</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'spdiary:ImageDelete' image.id %}">{% csrf_token %}
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">閉じる</button>
                    <button type="submit" class="btn btn-outline-success">削除</button>
                </form>
        </div>
        </div>
    </div>
</div>

templates/image/imagedetail.html
{% extends './base.html' %}
{% block content %}
<style>
    .title{/*タイトル*/
        left:20%;
        top:23%;
        position: absolute;
        font-size: 30px;
    }
    .photo{/*写真*/
        left:60%;
        top:20%;
        position: absolute;
    }
    .today{/*日付*/
        left:17%;
        top:43%;
        position: absolute;
        font-size: 20px;
    }
    .big{/*ボックス*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 20%;
        width: 300px;
        height: 80px;
        border-radius: 20px;
    }
    .box{/*メモ*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 40%;
        width: 400px;
        height: 150px;
        border-radius: 20px;

    }
    .memo{/*メモ本文*/
        left:17%;
        top:50%;
        position: absolute;
        font-size: 20px;
    }
    .delete{/*削除ボタン*/
        width: 150px;
        min-height: 44px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 35%;
        bottom: 23%;
    }    
</style>

<body>
    <div class="big"></div>
    <div class="box"></div>
    <div>
        <div class="title">{{ image.name }}</div>
        <div class="today">{{image.today|date:"m月d日"}}</div>
        <div class="memo">{{ image.memo }}</div>
        <div class="photo">
        <img src="{{ image.image.url  }}" width="300px">
        </div>
    </div>
    <button type="button" class="delete" data-bs-toggle="modal" data-bs-target="#deleteModal-{{image.id}}">削除する</button>
                            {% include 'image/ImageDelete.html' %}
</body>

{% endblock %}

templates/image/imagelist.html
{% extends './base.html' %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<style>
    .create{/*編集ボタン*/
      position:absolute;
      background-color:#bbf9c9;
      border-radius: 20px;
      left:72%;
      bottom:35%;
      color:rgb(237, 22, 18);
      font-size:18px;
      font-family: monospace;
      width: 210px;
      line-height: 38px;
      min-height: 48px; 
    }
    .list{/*ホームボタン*/
    border: none;
    position:absolute;
    background-color:#bbf9c9;
    border-radius: 20px;
    left:72%;
    bottom:23%;
    font-size:18px;
    font-family: monospace;
    width: 210px;
    line-height: 38px;
    min-height: 46px;   
    }
    .yohaku{
        margin:8px 45px;
    }

    .photo img{
    object-fit: cover;
    height: 200px;
    width: 200px;
  }

  input[name="query" ]{
    background-color: #FFF ;
    left:67%;
    position: absolute;
    font-size:21px;
    border-radius: 10px;
    top:19%;
  }

    .button{/*検索フォーム*/
    -moz-appearance: none;
    -webkit-appearance: none;
    appearance: none;

    margin: 1em 0; /* 前後の隙間 */
    padding: 0.6em 1em; /* 塗りの余白 */
    font-size: 1em; /* フォントサイズ */
    background-color: #9dc5a8; ; /* 背景色 */
    border: 0; /* 枠線を消す */
    transition: 0.3s; /* ホバーの変化を滑らかに */
    left:88.4%;
    position: absolute;
    border-radius: 10px; 
    top:16.5%;


  }
  .button:hover {/*検索ボタン*/
  background-color: #7d9f87; ; /* 背景色 */
  }


</style>
<body>
    <div class="big-box"></div>
    <div class="bg-light p-3 p-sm-5 mb-4 border-top">
      <div class="container">
        <h1 class="display-6">Welcome to "Memory Map"</h1>
        <p style="font-size:20px; padding-left:30%;">- PHOTO -</p>
      </div>
    </div>

    <div class="container">
      {% csrf_token%}
      <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text" placeholder="タイトルで検索"/>
        <button type="submit" class="button">検索する</button>
      </form>
    </div>

  <div class="container">    
  {% for image in image_list %}
  <div class="card mb-4" style="max-width: 540px; left:8%; background-color: #b8f7c7; border-radius:10px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{ image.image.url }}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'spdiary:ImageDetail' image.id %}">{{ image.name }}</a></h5>
          <p class="card-text"><small class="text-body-secondary">{{ image.today|date:"m月d日"}}</small></p>
          <h6 class="card-text">{{ image.memo }}</h6>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

<a class="list" href="{% url 'spdiary:list' %}"><span class="yohaku">日記作成 →</span></a>
<a class="create" href="{% url 'spdiary:Image' %}"><span class="yohaku">新規作成　→</span></a>
</body>
{% endblock %}