memo/urls.py
from django.contrib import admin
from django.urls import path,include#include追加する
from django.views.generic import RedirectView

from django.conf.urls.static import static # 追加
from django.conf import settings # 追加



urlpatterns = [
    path('admin/', admin.site.urls),
    path('spdiary/',include('spdiary.urls')),
    path('',RedirectView.as_view(url='/spdiary/login/')),
    #path('image/', include('spdiary.urls')), 

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 追加

spdiary/urls.py
from django.urls import path
#from .views import DiaryApp
from django.contrib.auth import views as auth_views
from .views import SignupPage
from .views import DiaryCreateView
from .views import DiaryListView
from .views import DiaryDetailView,DiaryUpdateView,DiaryDeleteView

from .views import ListPage,CreatePage,UpdatePage,DeletePage
from .views import ImageCreateView,ImageListView,ImageDetailView,ImageDeleteView

app_name = "spdiary"

urlpatterns = [
    #register
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignupPage.as_view(), name='signup'),
    #Diary
    path('create/', DiaryCreateView.as_view(), name='create'),
    path('list/', DiaryListView.as_view(), name='list'),
    path('detail/<uuid:pk>/',DiaryDetailView.as_view(), name = 'detail'), 
    path('update/<uuid:pk>/',DiaryUpdateView.as_view(), name = 'update'), 
    path('delete/<uuid:pk>/',DiaryDeleteView.as_view(),name='delete'),
    #imageリスト
    path('Image/',ImageCreateView.as_view(),name='Image'),
    path('ImageList/',ImageListView.as_view(),name='ImageList'),
    path('ImageDetail/<int:pk>/', ImageDetailView.as_view(), name='ImageDetail'),
    path('ImageDelete/<int:pk>/', ImageDeleteView.as_view(), name='ImageDelete'),
    #Todoリスト
    path('ListPage/',ListPage.as_view(),name='ListPage'),
    path('CreatePage/',CreatePage.as_view(),name='CreatePage'),
    path('UpdatePage/<int:pk>/',UpdatePage.as_view(),name='UpdatePage'),
    path('DeletePage/<int:pk>/',DeletePage.as_view(),name='DeletePage'),
]

spdiary/models.py
from django.db import models
from django.utils import timezone#追加する
import uuid#追加する
from django.contrib.auth.models import User

class Todo(models.Model):
    time = models.DateField(verbose_name="作成日", default=timezone.now)
    memo = models.TextField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)#自動でつく
    date = models.DateField(verbose_name='日付', default=timezone.now)#日付
    title = models.CharField(verbose_name='タイトル', max_length=255)#日付のタイトル
    text = models.TextField(verbose_name='本文',blank=True,null=True,max_length=1000)#日付の本文
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)#作成日時
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)#編集日時
    tagname = models.CharField(verbose_name='タグ', max_length=40,null=True,blank=True)#タグを書くスペース
    tag = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    def __str__(self):
            return self.title
    

class Image(models.Model):
    name = models.CharField(verbose_name='題名',max_length=40)
    image = models.ImageField(upload_to='img/upload')
    memo = models.TextField(verbose_name='メモ',max_length=60,null=True,blank=True)
    today = models.DateTimeField(verbose_name='作成日', default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
     
    def __str__(self):
            return self.name

templates/diary/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="ja">   
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memory Map</title>
</head>
<body style="padding-top: 4rem;">

    <div class='fixed-top'>
        <nav class="navbar navbar-expand-lg" style="background-color:#b8f7c7; font-size: 20px;">
            <a class="navbar-brand" href="{% url 'spdiary:list' %}">&nbsp;&nbsp;&nbsp;Memory Map<span class="sr-only"></span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'spdiary:list' %}">&nbsp;&nbsp;&nbsp;DIARY</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'spdiary:ListPage' %}">&nbsp;&nbsp;&nbsp;TODO</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'spdiary:ImageList' %}">&nbsp;&nbsp;&nbsp;PHOTO</a>
              </ul>
            </div>

            <ul class="navbar-nav mr-md-2">
                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'spdiary:logout' %}">ログアウト</a></li>
                </ul>
                {% else %}
                <a class="btn btn-outline-light btn-sm" href="{% url 'spdiary:login' %}">ログイン</a></li>
                {% endif %}
            </ul>  
        </nav>  
    </div>

    
    {% block content %}
    {% endblock %}
</body>
</html>

templates/diary/create.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block content %}

<style>
    .button{/*submit*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 35%;
    }
    .back{/*戻るボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 25%;
    }
    .yohaku1{
        margin:0px 40px;
    }

    .date{/*日付ボックス*/
        width: 250px;
        min-height: 46px;
        background-color: #b8f7c7;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 10%;
        top: 15%;
        font-size: 20px;
    }
    .tag-box{/*テキスト本文*/
        color: #000000;
        position: absolute;
        left:10%;
        top: 26%;
    }
    .date-box{/*日付*/
        position: absolute;
        color:#000000;
        left:10%;
        top:12%;
    }
    .text-box{/*背景のボックス*/
        color: #000000;
        position: absolute;
        left:10%;
        top: 49%;
    }
    .small{
        color: #000000;
        position: absolute;
        left:10%;
        top: 37%;
    }
    #id_tagname{/*タグボックス*/
        background-color:#b8f7c7;
        width: 400px;
        position: absolute;
        min-height: 46px;
        border: none;
        border-radius: 20px;
        left: 10%;
        top: 30%;
        font-size: 20px;
    }
    #id_title{/*タイトル*/
        background-color:#b8f7c7;
        width: 450px;
        position: absolute;
        min-height: 46px;
        border: none;
        border-radius: 20px;
        left: 10%;
        top: 40%;
        font-size: 20px;
    }
    #id_text{/*テキスト*/
        background-color:#b8f7c7;
        width: 600px;
        position: absolute;
        min-height: 230px;
        border: none;
        border-radius: 20px;
        left: 10%;
        top: 53%;
        font-size: 17px;
    }
</style>
    <div class="date"></div>
    <div class="date-box">日付</div>
    <div class="small">タイトル</div>
    <div class="tag-box">ハッシュタグ機能(#の後にタグ名を記入) </div>
    <div class="text-box">日記</div>
    <form method="post">    
        {% csrf_token %}
  
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.date|add_class:"date"}}
        </div>
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.title|add_class:"title"}}
        </div>
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.tagname|add_class:"tagname"}}
        </div>
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.text|add_class:"text"}}
        <div>
            <input class="button div" type="submit" value="追加する →">
        </div>
        </form>
    </form>
    <a class="back" href="{% url 'spdiary:list'  %}"><span class="yohaku1">戻る →</span></a>
{% endblock %}    

templates/diary/delete.html
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{diary.id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">日記の削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>日記を削除してもよろしいですか ?</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'spdiary:delete' diary.id %}">{% csrf_token %}
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">閉じる</button>
                    <button type="submit" class="btn btn-outline-success">削除</button>
                </form>
        </div>
        </div>
    </div>
</div>

templates/diary/detail.html
{% extends './base.html' %}
{% load static %}
{% block content %}
<style>
    @media screen and (-webkit-min-device-pixel-ratio:0){
    .date{/*日付ボックス*/
        width: 250px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 42px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 10%;
        top: 15%;
    }
    .yohaku{
        margin:0px 20px;
    }
    .text-box{/*背景のボックス*/
        background-color: #b8f7c7;
        position: absolute;
        left:10%;
        top: 40%;
        width: 650px;
        height: 300px;
        border-radius: 20px;
    }
    .title{/*タイトル*/
        position:absolute;
        padding-top:19%; 
        left:14%;
        color:rgb(0, 0, 0);
        font-size:25px;
        z-index:999;
        font-family: monospace;
    }
    .create{/*編集ボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 35%;
    }
    .delete{/*削除ボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 25%;
    }    
    .yohaku1{
        margin:0px 40px;
    }
    .text{/*内容*/
        position:absolute;
        padding-top:23%; 
        left:16%;
        color:rgb(0, 0, 0);
        font-size:16px;
        z-index:999;
        font-family: monospace;
        width: 30em;
    }
    .tag{/*タグ機能*/
        position:absolute;
        top:29.6%; 
        left:12%;
        color:rgb(0, 0, 0);
        font-size:20px;
        z-index:999;
        font-family: monospace;
        width: 30em;
    }
    .tag-box{/*テキスト*/
        background-color: #b8f7c7;
        position: absolute;
        left:10%;
        top: 28%;
        width: 400px;
        height: 50px;
        border-radius: 20px;

    }
}
</style>

<div class="text-box"></div>
<div class="tag-box"></div>
<div class="date"><span class="yohaku">日付：{{ diary.date|date:" Y年m月d日" }}</span></div> 
<div class="title"><u>{{ diary.title }}</u></div>
<div class="text">{{ diary.text }}</div>
<div class="tag">タグ：{{ diary.tagname }}</div>
<a class="create" href="{% url 'spdiary:update' diary.id %}"><span class="yohaku1">編集 →</span></a>
<!--<a class="delete" href="{% url 'spdiary:delete' diary.id %}"><span class="yohaku1">削除 →</span></a>-->
<button type="button" class="delete" data-bs-toggle="modal" data-bs-target="#deleteModal-{{diary.pk}}">削除する</button>
                            {% include 'diary/delete.html' %}
</body>
</html>
{% endblock %}

templates/diary/list.html
{% extends './base.html' %}
{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css" integrity="sha384-BY+fdrpOd3gfeRvTSMT+VUZmA728cfF9Z2G42xpaRkUGu2i3DyzpTURDo5A6CaLK" crossorigin="anonymous">
<body>

<style>
  input[name="tag" ]{
    background-color: #FFF ;
    left:67%;
    position: absolute;
    font-size:21px;
    border-radius: 10px;
    top:19%;
  }
  .button{/*検索フォーム*/
    -moz-appearance: none;
    -webkit-appearance: none;
    appearance: none;

    margin: 1em 0; /* 前後の隙間 */
    padding: 0.6em 1em; /* 塗りの余白 */
    font-size: 1em; /* フォントサイズ */
    background-color: #9dc5a8; ; /* 背景色 */
    border: 0; /* 枠線を消す */
    transition: 0.3s; /* ホバーの変化を滑らかに */
    left:88.4%;
    position: absolute;
    border-radius: 10px; 
    top:16.5%;

  }
  .button:hover {/*検索ボタン*/
  background-color: #7d9f87; ; /* 背景色 */
}

  .fake-box{/*リストのボックス*/
    background-color: #b8f7c7; ;
    position: absolute;
    left: 65.7%;
    top: 15%;
    width: 400px;
    height: 100px;
    border-radius: 20px;
}

  .list{/*リストの内容*/
    position:absolute;
    padding-top: 80px; 
    left:450px;
    color:rgb(0, 0, 0);
    font-size:30px;
    z-index:999;
    font-family: monospace;
  }
  .card-header{/*リスト*/
    position:absolute;
    color:rgb(0, 0, 0);
    font-size:18px;
    z-index:999;
    font-family: monospace;
    background-color: #ffffff ;
    width: 450px;
    height: 40px;
  }


  .create{/*新規作成ボタン*/
    position:absolute;
    background-color:#bbf9c9;
    border-radius: 20px;
    left:72%;
    bottom:35%;
    color:rgb(237, 18, 18);
    font-size:18px;
    font-family: monospace;
    width: 210px;
    line-height: 38px;
    min-height: 48px;
  }
  .photo{/*写真ボタン*/
    border: none;
    position:absolute;
    background-color:#bbf9c9;
    border-radius: 20px;
    left:72%;
    bottom:23%;
    font-size:18px;
    font-family: monospace;
    width: 210px;
    line-height: 38px;
    min-height: 46px;
  }
  .yohaku{/*余白*/
	margin:4px 40px;
  }


</style>
<!--<div class="fake-box"></div>-->

<body>
  <div class="big-box"></div>
  <div class="bg-light p-3 p-sm-5 mb-4 border-top">
    <div class="container">
      <h1 class="display-6">Welcome to "Memory Map"</h1>
      <p style="font-size:20px; padding-left:30%;">- DIARY -</p>
    </div>
  </div>

  <div class="container">
    {% csrf_token%}
    <form action="" method="get">
      <input name="tag" value="{{ request.GET.tag }}" type="text" placeholder="#のワードを検索"/>
      <button type="submit"class="button">検索する</button>
    </form>

    <ul>
    {% for diary in diary_list %}
    <div class="card my-5" style="width: 40rem;height: 150px; border-radius: 20px; background-color: #b8f7c7;">
        <div class="card-header" style="border-radius: 40px; top:10%; left:5%;"><strong>タイトル:<a href="{% url 'spdiary:detail' diary.id %}">{{diary.title}}</a></strong></div>
        <div class="card-body" style="position:absolute; left:5%; top:40%; font-size:15px; font-family: monospace;">{{ diary.date|date:" m月d日" }}<br>{{ diary.text|truncatechars_html:30|linebreaksbr}}</div>
    </div>
    {% endfor %}
    </ul>
  </div>
  <a class="create" href="{% url 'spdiary:create' %}"><span class="yohaku">新規作成 →</span></a>
  <a class="photo" href="{% url 'spdiary:Image' %}"><span class="yohaku">写真追加 →</span></a>
</body>
{% endblock %}

templates/diary/update.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block content %}
<style>
    .date{/*日付ボックス*/
        width: 250px;
        min-height: 46px;
        background-color: #b8f7c7;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 10%;
        top: 15%;
        font-size: 20px;
    }
    #id_tagname{/*タグ機能*/
        background-color:#b8f7c7;
        width: 400px;
        position: absolute;
        min-height: 46px;
        border: none;
        border-radius: 20px;
        left: 10%;
        top: 27%;
        font-size: 20px;
    }
    #id_title{/*タイトル*/
        background-color:#b8f7c7;
        width: 450px;
        position: absolute;
        min-height: 46px;
        border: none;
        border-radius: 20px;
        left: 10%;
        top: 38%;
        font-size: 20px;
    }
    #id_text{/*テキスト*/
        background-color:#b8f7c7;
        width: 600px;
        position: absolute;
        min-height: 230px;
        border: none;
        border-radius: 20px;
        left: 10%;
        top: 50%;
        font-size: 20px;
    }
    .update-button{/*更新ボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 35%;
    }
    .back{/*戻るボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 25%;
    }
    .yohaku1{
        margin:0px 40px;
    }

</style>
<form action="" method="POST">
    {% csrf_token %}
    <!--<div class="form-group">
        <label>{{ form.date.label }}</label>
        {% render_field form.date class+="form-control w-25 mb-4" %}
    </div>
    <div class="form-group">
        <label>{{ form.title.label }}</label>
        {% render_field form.title class+="form-control w-25 mb-4" %}
    </div>
    <div class="form-group">
        <label>{{ form.tagname.label }}</label>
        {% render_field form.tagname class+="form-control w-25 mb-4" %}
    </div>   
    <div class="form-group">
        <label>{{ form.text.label }}</label>
        {% render_field form.text class+="form-control w-25 mb-4" %}
    </div>-->
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.date|add_class:"date"}}
    </div>
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.title|add_class:"title"}}
    </div>
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.tagname|add_class:"tagname"}}
    </div>
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.text|add_class:"text"}}
    <div>
    <div>
        <input class="update-button div" type="submit" value="更新する">
    </div>
</form>
<a class="back" href="{% url 'spdiary:list'  %}"><span class="yohaku1">戻る →</span></a>
{% endblock %}