memo/urls.py
from django.contrib import admin
from django.urls import path,include#include追加する
from django.views.generic import RedirectView

from django.conf.urls.static import static # 追加
from django.conf import settings # 追加



urlpatterns = [
    path('admin/', admin.site.urls),
    path('spdiary/',include('spdiary.urls')),
    path('',RedirectView.as_view(url='/spdiary/login/')),
    #path('image/', include('spdiary.urls')), 

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 追加

spdiary/urls.py
from django.urls import path
#from .views import DiaryApp
from django.contrib.auth import views as auth_views
from .views import SignupPage
from .views import DiaryCreateView
from .views import DiaryListView
from .views import DiaryDetailView,DiaryUpdateView,DiaryDeleteView

from .views import ListPage,CreatePage,UpdatePage,DeletePage
from .views import ImageCreateView,ImageListView,ImageDetailView,ImageDeleteView

app_name = "spdiary"

urlpatterns = [
    #register
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignupPage.as_view(), name='signup'),
    #Diary
    path('create/', DiaryCreateView.as_view(), name='create'),
    path('list/', DiaryListView.as_view(), name='list'),
    path('detail/<uuid:pk>/',DiaryDetailView.as_view(), name = 'detail'), 
    path('update/<uuid:pk>/',DiaryUpdateView.as_view(), name = 'update'), 
    path('delete/<uuid:pk>/',DiaryDeleteView.as_view(),name='delete'),
    #imageリスト
    path('Image/',ImageCreateView.as_view(),name='Image'),
    path('ImageList/',ImageListView.as_view(),name='ImageList'),
    path('ImageDetail/<int:pk>/', ImageDetailView.as_view(), name='ImageDetail'),
    path('ImageDelete/<int:pk>/', ImageDeleteView.as_view(), name='ImageDelete'),
    #Todoリスト
    path('ListPage/',ListPage.as_view(),name='ListPage'),
    path('CreatePage/',CreatePage.as_view(),name='CreatePage'),
    path('UpdatePage/<int:pk>/',UpdatePage.as_view(),name='UpdatePage'),
    path('DeletePage/<int:pk>/',DeletePage.as_view(),name='DeletePage'),
]

spdiary/models.py
from django.db import models
from django.utils import timezone#追加する
import uuid#追加する
from django.contrib.auth.models import User

class Todo(models.Model):
    time = models.DateField(verbose_name="作成日", default=timezone.now)
    memo = models.TextField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)#自動でつく
    date = models.DateField(verbose_name='日付', default=timezone.now)#日付
    title = models.CharField(verbose_name='タイトル', max_length=255)#日付のタイトル
    text = models.TextField(verbose_name='本文',blank=True,null=True,max_length=1000)#日付の本文
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)#作成日時
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)#編集日時
    tagname = models.CharField(verbose_name='タグ', max_length=40,null=True,blank=True)#タグを書くスペース
    tag = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    def __str__(self):
            return self.title
    

class Image(models.Model):
    name = models.CharField(verbose_name='題名',max_length=40)
    image = models.ImageField(upload_to='img/upload')
    memo = models.TextField(verbose_name='メモ',max_length=60,null=True,blank=True)
    today = models.DateTimeField(verbose_name='作成日', default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
     
    def __str__(self):
            return self.name

templates/todo/CreatePage.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block content %}
<style>
    .button{/*作成ボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 35%;
    }
    .back{/*戻るボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 25%;
    }

    #id_time{ /*日付*/
        background-color: #b8f7c7;
        left:28%;
        top:42.9%;
        width: 200px;
        position: absolute;
    }
    #id_memo{/*メモ*/
        background-color:#b8f7c7;
        left:25%;
        top:58.9%;
        width: 300px;
        position: absolute;
        border-radius: 20px;
        font-size: 20px;
    }
    .yohaku1{
        margin:0px 40px;
    }
    .memo{/*メモボックス*/
        background-color: #b8f7c7;
        position: absolute;
        left:25%;
        top: 42%;
        width: 300px;
        height: 50px;
        border-radius: 20px;
    }

    .tome{/*背景ボックス*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 30%;
        width: 650px;
        height: 350px;
        border-radius: 20px;
        opacity: 0.3;
    }

</style>

<div class="tome"></div>
<div class="big"></div>
<form method="post">
    {% csrf_token %}
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.time|add_class:"time"}}
        </div>
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.memo|add_class:"memo"}}
        </div>
    <input class="button div" type="submit" value="追加する →">
</form>
<a class="back" href="{% url 'spdiary:Listpage'  %}"><span class="yohaku1">戻る →</span></a>

{% endblock %}

templates/todo/DeletePage.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<style>
    .delete-button{/*削除ボタン*/
        width: 160px;
        min-height: 46px;
        background-color: #f5d4da;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 40px;
        position: absolute;
        left: 100px;
        bottom: 150px;
    }
</style>
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{item.pk}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">MEMOの削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>「{{ item.memo }}」を削除してもよろしいですか ?</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'spdiary:DeletePage' item.pk %}">{% csrf_token %}
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">閉じる</button>
                    <button type="submit" class="btn btn-outline-success">削除</button>
                </form>
        </div>
        </div>
    </div>
</div>

templates/todo/ListPage.html
{% extends './base.html' %}
{% block content %}
<style>
    .createpage{/*編集ボタン*/
    width: 210px;
    min-height: 46px;
    background-color: #bbf9c9;
    font-size: 18px;
    font-family: monospace;
    line-height: 38px;
    border: none;
    color:rgb(237, 18, 18);
    border-radius: 20px;
    position: absolute;
    left: 65%;
    top: 25%;    
    }
    .homepage{/*ホームボタン*/
    width: 210px;
    min-height: 46px;
    background-color: #b8f7c7;
    font-size: 18px;
    font-family: monospace;
    line-height: 38px;
    border: none;
    border-radius: 20px;
    position: absolute;
    left: 65%;
    top: 14%;    
    }
    .yohaku{
        margin:4px 40px;
    }

    .form-check{
    left:5%;
    }

    input[name="query" ]{
    background-color: #ffffff;;
    left:65%;
    position: absolute;
    font-size:21px;
    border-radius: 10px;
    top:38%;
  }

    .button{/*検索フォーム*/
    -moz-appearance: none;
    -webkit-appearance: none;
    appearance: none;

    margin: 1em 0; /* 前後の隙間 */
    padding: 0.6em 1em; /* 塗りの余白 */
    font-size: 1em; /* フォントサイズ */
    background-color: #9dc5a8; ; /* 背景色 */
    border: 0; /* 枠線を消す */
    transition: 0.3s; /* ホバーの変化を滑らかに */
    position: absolute;
    border-radius: 10px; 
    top:35%;
    left:88%;

  }
  .button:hover {/*検索ボタン*/
  background-color: #7d9f87; ; /* 背景色 */
  }

</style>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<body>
    <div class="big-box"></div>
    <div class="bg-light p-3 p-sm-5 mb-4 border-top">
    <div class="container">
      <h1 class="display-6">Welcome to "Memory Map"</h1>
      <p style="font-size:20px; padding-left:30%;">- TODO -</p>
    </div>
    </div>

    <div class="container">
    {% csrf_token%}
    <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text" placeholder="メモを検索"/>
        <button type="submit"class="button">検索する</button>
    </form>
    </div>  
     
    <ul>
        <div class="container">
            <table class="table caption-top my-5">
            <!--<caption>TODO</caption>-->
                <thead>
                    <tr>
                        <th scope="col">○DONE</th>
                        <th scope="col">○DATE</th>
                        <th scope="col">○MEMO</th>
                        <th scope="col"></th>
                    </tr>
                    <tbody>
                    {% for item in object_list %}
                    <tr>
                        <th><div class="form-check">
                            <input class="form-check-input position-static" type="checkbox">
                          </div></th>
                        <th>{{ item.time|date:" m月d日" }}</th>
                        <th>{{ item.memo }}</th>
                        <th><a href="{% url 'spdiary:UpdatePage' item.pk %}">編集する</a></th>
                        <th><button type="button" class="btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal-{{item.pk}}">削除する</button>
                            {% include 'todo/deletepage.html' %}</th>
                    </tr>
                    {% endfor %}
                    </tbody>
                </thead>
            </table>
        </div>            
    </ul>
<a class="createpage" href="{% url 'spdiary:CreatePage' %}"><span class="yohaku">新規作成 →</span></a>
<a class="homepage" href="{% url 'spdiary:list' %}"><span class="yohaku">日記 →</span></a>
{% endblock %}
</body>

templates/todo/UpdatePage.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block content %}
<style>
    .update-button{/*更新ボタン*/
        width: 160px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 40px;
        position: absolute;
        left: 80%;
        bottom: 150px;
    }
    #id_time{ /*日付*/
        background-color: #b8f7c7;
        left:28%;
        top:43%;
        width: 200px;
        position: absolute;
    }
    #id_memo{/*メモ*/
        background-color:#b8f7c7;
        left:25%;
        top:58.4%;
        width: 300px;
        position: absolute;
    }
    .yohaku1{
        margin:0px 40px;
    }
    .big{/*背景*/
        background-color: #b8f7c7;
        position: absolute;
        left:25%;
        top: 42%;
        width: 300px;
        height: 50px;
        border-radius: 20px;
    }
    .memo{/*メモ本文*/
        background-color: #b8f7c7;
        position: absolute;
        left:25%;
        top: 58%;
        width: 400px;
        height: 50px;
        border-radius: 20px;

    }
    .tome{/*背景*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 30%;
        width: 650px;
        height: 350px;
        border-radius: 20px;
        opacity: 0.3;
    }

</style>
<div class="tome"></div>

<div class="big"></div>
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.time|add_class:"time"}}
    <div>
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.memo|add_class:"memo"}}
    <div>
    <div>
        <input class="update-button div" type="submit" value="更新する">
    </div>
</form>
{% endblock %}

templates/todo/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="ja">   
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memory Map</title>
</head>
<body style="padding-top: 4rem;">

    <div class='fixed-top'>
        <nav class="navbar navbar-expand-lg" style="background-color:#b8f7c7; font-size: 20px;">
            <a class="navbar-brand" href="{% url 'spdiary:list' %}">&nbsp;&nbsp;&nbsp;Memory Map<span class="sr-only"></span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'spdiary:list' %}">&nbsp;&nbsp;&nbsp;DIARY</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'spdiary:ListPage' %}">&nbsp;&nbsp;&nbsp;TODO</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'spdiary:ImageList' %}">&nbsp;&nbsp;&nbsp;PHOTO</a>
              </ul>
            </div>

            <ul class="navbar-nav mr-md-2">
                {% if user.is_authenticated %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'spdiary:logout' %}">ログアウト</a></li>
                </ul>
                {% else %}
                <a class="btn btn-outline-light btn-sm" href="{% url 'spdiary:login' %}">ログイン</a></li>
                {% endif %}
            </ul>  
        </nav>  
    </div>

    
    {% block content %}
    {% endblock %}
</body>
</html>

templates/todo/createpage.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block content %}
<style>
    .button{/*作成ボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 35%;
    }
    .back{/*戻るボタン*/
        width: 170px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        line-height: 38px;
        border: none;
        border-radius: 20px;
        position: absolute;
        left: 70%;
        bottom: 25%;
    }

    #id_time{ /*日付*/
        background-color: #b8f7c7;
        left:28%;
        top:42.9%;
        width: 200px;
        position: absolute;
    }
    #id_memo{/*メモ*/
        background-color:#b8f7c7;
        left:25%;
        top:58.9%;
        width: 300px;
        position: absolute;
        border-radius: 20px;
        font-size: 20px;
    }
    .yohaku1{
        margin:0px 40px;
    }
    .memo{/*メモボックス*/
        background-color: #b8f7c7;
        position: absolute;
        left:25%;
        top: 42%;
        width: 300px;
        height: 50px;
        border-radius: 20px;
    }

    .tome{/*背景ボックス*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 30%;
        width: 650px;
        height: 350px;
        border-radius: 20px;
        opacity: 0.3;
    }

</style>

<div class="tome"></div>
<div class="big"></div>
<form method="post">
    {% csrf_token %}
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.time|add_class:"time"}}
        </div>
        <div class="form-group mb-3">
            <label for="formGroupExampleInput"></label>
            {{ form.memo|add_class:"memo"}}
        </div>
    <input class="button div" type="submit" value="追加する →">
</form>
<a class="back" href="{% url 'spdiary:Listpage'  %}"><span class="yohaku1">戻る →</span></a>

{% endblock %}

templates/todo/deletepage.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<style>
    .delete-button{/*削除ボタン*/
        width: 160px;
        min-height: 46px;
        background-color: #f5d4da;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 40px;
        position: absolute;
        left: 100px;
        bottom: 150px;
    }
</style>
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{item.pk}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">MEMOの削除</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>「{{ item.memo }}」を削除してもよろしいですか ?</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'spdiary:DeletePage' item.pk %}">{% csrf_token %}
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">閉じる</button>
                    <button type="submit" class="btn btn-outline-success">削除</button>
                </form>
        </div>
        </div>
    </div>
</div>

templates/todo/listpage.html
{% extends './base.html' %}
{% block content %}
<style>
    .createpage{/*編集ボタン*/
    width: 210px;
    min-height: 46px;
    background-color: #bbf9c9;
    font-size: 18px;
    font-family: monospace;
    line-height: 38px;
    border: none;
    color:rgb(237, 18, 18);
    border-radius: 20px;
    position: absolute;
    left: 65%;
    top: 25%;    
    }
    .homepage{/*ホームボタン*/
    width: 210px;
    min-height: 46px;
    background-color: #b8f7c7;
    font-size: 18px;
    font-family: monospace;
    line-height: 38px;
    border: none;
    border-radius: 20px;
    position: absolute;
    left: 65%;
    top: 14%;    
    }
    .yohaku{
        margin:4px 40px;
    }

    .form-check{
    left:5%;
    }

    input[name="query" ]{
    background-color: #ffffff;;
    left:65%;
    position: absolute;
    font-size:21px;
    border-radius: 10px;
    top:38%;
  }

    .button{/*検索フォーム*/
    -moz-appearance: none;
    -webkit-appearance: none;
    appearance: none;

    margin: 1em 0; /* 前後の隙間 */
    padding: 0.6em 1em; /* 塗りの余白 */
    font-size: 1em; /* フォントサイズ */
    background-color: #9dc5a8; ; /* 背景色 */
    border: 0; /* 枠線を消す */
    transition: 0.3s; /* ホバーの変化を滑らかに */
    position: absolute;
    border-radius: 10px; 
    top:35%;
    left:88%;

  }
  .button:hover {/*検索ボタン*/
  background-color: #7d9f87; ; /* 背景色 */
  }

</style>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<body>
    <div class="big-box"></div>
    <div class="bg-light p-3 p-sm-5 mb-4 border-top">
    <div class="container">
      <h1 class="display-6">Welcome to "Memory Map"</h1>
      <p style="font-size:20px; padding-left:30%;">- TODO -</p>
    </div>
    </div>

    <div class="container">
    {% csrf_token%}
    <form action="" method="get">
        <input name="query" value="{{ request.GET.query }}" type="text" placeholder="メモを検索"/>
        <button type="submit"class="button">検索する</button>
    </form>
    </div>  
     
    <ul>
        <div class="container">
            <table class="table caption-top my-5">
            <!--<caption>TODO</caption>-->
                <thead>
                    <tr>
                        <th scope="col">○DONE</th>
                        <th scope="col">○DATE</th>
                        <th scope="col">○MEMO</th>
                        <th scope="col"></th>
                    </tr>
                    <tbody>
                    {% for item in object_list %}
                    <tr>
                        <th><div class="form-check">
                            <input class="form-check-input position-static" type="checkbox">
                          </div></th>
                        <th>{{ item.time|date:" m月d日" }}</th>
                        <th>{{ item.memo }}</th>
                        <th><a href="{% url 'spdiary:UpdatePage' item.pk %}">編集する</a></th>
                        <th><button type="button" class="btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal-{{item.pk}}">削除する</button>
                            {% include 'todo/deletepage.html' %}</th>
                    </tr>
                    {% endfor %}
                    </tbody>
                </thead>
            </table>
        </div>            
    </ul>
<a class="createpage" href="{% url 'spdiary:CreatePage' %}"><span class="yohaku">新規作成 →</span></a>
<a class="homepage" href="{% url 'spdiary:list' %}"><span class="yohaku">日記 →</span></a>
{% endblock %}
</body>

templates/todo/updatepage.html
{% extends './base.html' %}
{% load widget_tweaks %}
{% block content %}
<style>
    .update-button{/*更新ボタン*/
        width: 160px;
        min-height: 46px;
        background-color: #b8f7c7;
        font-size: 18px;
        font-family: monospace;
        color: #000000 ;
        line-height: 38px;
        border: none;
        border-radius: 40px;
        position: absolute;
        left: 80%;
        bottom: 150px;
    }
    #id_time{ /*日付*/
        background-color: #b8f7c7;
        left:28%;
        top:43%;
        width: 200px;
        position: absolute;
    }
    #id_memo{/*メモ*/
        background-color:#b8f7c7;
        left:25%;
        top:58.4%;
        width: 300px;
        position: absolute;
    }
    .yohaku1{
        margin:0px 40px;
    }
    .big{/*背景*/
        background-color: #b8f7c7;
        position: absolute;
        left:25%;
        top: 42%;
        width: 300px;
        height: 50px;
        border-radius: 20px;
    }
    .memo{/*メモ本文*/
        background-color: #b8f7c7;
        position: absolute;
        left:25%;
        top: 58%;
        width: 400px;
        height: 50px;
        border-radius: 20px;

    }
    .tome{/*背景*/
        background-color: #b8f7c7;
        position: absolute;
        left:15%;
        top: 30%;
        width: 650px;
        height: 350px;
        border-radius: 20px;
        opacity: 0.3;
    }

</style>
<div class="tome"></div>

<div class="big"></div>
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.time|add_class:"time"}}
    <div>
    <div class="form-group mb-3">
        <label for="formGroupExampleInput"></label>
        {{ form.memo|add_class:"memo"}}
    <div>
    <div>
        <input class="update-button div" type="submit" value="更新する">
    </div>
</form>
{% endblock %}